6.3.7 (2013-03-19) - Server init script was rewritten to be compatible with other Linux distributions.

diff --git a/client/serverusage_client b/client/serverusage_client
--- a/client/serverusage_client
+++ b/client/serverusage_client
@@ -6,8 +6,8 @@
 #==============================================================================+
 # File name   : serverusage_client
 # Begin       : 2012-04-12
-# Last Update : 2012-09-18
-# Version     : 6.3.6
+# Last Update : 2013-03-19
+# Version     : 6.3.7
 #
 # Description : Init script to execute ServerUsage-Client.
 #
@@ -62,7 +62,9 @@ fi
 # commands to execute (systemtap monitoring + tcp sender)
 CMDSTAP="$PATH_STAPRUN -b $BUFFER_SIZE $PATH_STAPMODULE smp=$SAMPLING_TIME srvid=$SERVER_ID"
 CMDTCPS="$PATH_TCPSENDER $LOGSERVER_IP $LOGSERVER_PORT $PATH_TEMPLOG"
-LOCKFILE=/var/lock/subsys/serverusage_client
+LOCKFILE="/var/lock/serverusage_client"
+PID=`ps ax | grep -v grep | grep "$PATH_STAPIO" | awk '{print $1;}'`
+PIDB=`ps ax | grep -v grep | grep "$PATH_TCPSENDER" | awk '{print $1;}'`
 RETVAL=0
 
 # get SystemV Init function library.
@@ -70,16 +72,19 @@ if [ -f /etc/init.d/functions ] ; then
 	. /etc/init.d/functions
 elif [ -f /etc/rc.d/init.d/functions ] ; then
 	. /etc/rc.d/init.d/functions
+elif [ -f /lib/lsb/init-functions ] ; then
+	. /lib/lsb/init-functions
 else
 	exit 1
 fi
 
 # Start the service
 start() {
+	echo -n "Starting ServerUsage-Client: "
 	if test -f $LOCKFILE ; then
 		# check if the process is running
-		if [ ! -z "`ps ax | grep -v grep | grep $PATH_STAPIO`" ] && [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPSENDER`" ]; then
-			echo -n $"Service is Already Running."
+		if [ ! -z "$PID" ] && [ ! -z "$PIDB" ]; then
+			echo -n "Service is Already Running."
 			echo
 			return
 		else
@@ -87,30 +92,29 @@ start() {
 			rm -f $LOCKFILE
 		fi
 	fi
-	echo -n $"Starting ServerUsage-Client: "
 	(setsid bash -c "($CMDSTAP | $CMDTCPS) & disown %%") </dev/null >&/dev/null &
 	RETVAL=$?
-	[ $RETVAL = 0 ] && touch $LOCKFILE && success || failure
-	echo
+	[ $RETVAL = 0 ] && touch $LOCKFILE && echo "OK" || echo "ERROR"
 	return $RETVAL
 }
 
 # Restart the service
 stop() {
-	echo -n $"Stopping ServerUsage-Client: "
+	echo -n "Stopping ServerUsage-Client: "
 	# check if the process is running
-	if [ ! -z "`ps ax | grep -v grep | grep $PATH_STAPIO`" ]; then
+	if [ ! -z "$PID" ]; then
 		# kill the process
-		killproc $PATH_STAPIO
+		kill $PID
 		RETVAL=$?
+		echo "OK"
 	else
-		failure $"ServerUsage-Client stop"
+		RETVAL=3
+		echo "Service is not running."
 	fi
-	if [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPSENDER`" ]; then
+	if [ ! -z "$PIDB" ]; then
 		# kill the process
-		killproc $PATH_TCPSENDER
+		kill $PIDB
 	fi
-	echo
 	rm -f $LOCKFILE
 	return $RETVAL
 }
@@ -124,9 +128,19 @@ case "$1" in
 		stop
 		;;
 	status)
-		status $PATH_STAPIO
-		RETVAL=$?
-		status $PATH_TCPSENDER
+		echo -n "ServerUsage-Client status: "
+		if [ ! -z "$PID" ] && [ ! -z "$PIDB" ]; then
+			RETVAL=0
+			echo "Service is running."
+		else
+			if test -f $LOCKFILE ; then
+				RETVAL=2
+				echo "Service is dead and $LOCKFILE lock file exist."
+			else
+				RETVAL=3
+				echo "Service is not running."
+			fi
+		fi
 		;;
 	restart|reload)
 		stop
@@ -139,7 +153,7 @@ case "$1" in
 		fi
 		;;
 	*)
-		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
+		echo "Usage: $0 {start|stop|status|restart|reload|condrestart}"
 		RETVAL=2
 		[ "$1" = 'usage' ] && RETVAL=0
 esac
diff --git a/server/serverusage_server b/server/serverusage_server
--- a/server/serverusage_server
+++ b/server/serverusage_server
@@ -6,8 +6,8 @@
 #==============================================================================+
 # File name   : serverusage_server
 # Begin       : 2012-04-12
-# Last Update : 2012-09-18
-# Version     : 6.3.6
+# Last Update : 2013-03-19
+# Version     : 6.3.7
 #
 # Description : Init script to execute ServerUsage-Server.
 #
@@ -27,7 +27,7 @@
 #               support@fubra.com
 #
 # License:
-#    Copyright (C) 2012-2012 Fubra Limited
+#    Copyright (C) 2012-2013 Fubra Limited
 #
 #    This program is free software: you can redistribute it and/or modify
 #    it under the terms of the GNU Affero General Public License as
@@ -55,7 +55,8 @@ fi
 
 # start program in background
 CMD="$PATH_TCPRECEIVER $LOGSERVER_PORT $MAX_CONNECTIONS $SQLITE_DATABASE"
-LOCKFILE=/var/lock/subsys/serverusage_server
+LOCKFILE="/var/lock/serverusage_server"
+PID=`ps ax | grep -v grep | grep "$CMD" | awk '{print $1;}'`
 RETVAL=0
 
 # get SystemV Init function library.
@@ -63,29 +64,30 @@ if [ -f /etc/init.d/functions ] ; then
 	. /etc/init.d/functions
 elif [ -f /etc/rc.d/init.d/functions ] ; then
 	. /etc/rc.d/init.d/functions
+elif [ -f /lib/lsb/init-functions ] ; then
+	. /lib/lsb/init-functions
 else
 	exit 1
 fi
 
 # Start the service
 start() {
+	echo -n "Starting ServerUsage-Server: "
 	if test -f $LOCKFILE ; then
 		# check if the process is running
-		if [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPRECEIVER`" ]; then
-			echo -n $"Service is Already Running."
+		if [ ! -z "$PID" ]; then
+			echo -n "Service is Already Running."
 			echo
-			return
+			return $RETVAL
 		else
 			# delete the orphan lock file
 			rm -f $LOCKFILE
 		fi
 	fi
-	echo -n $"Starting ServerUsage-Server: "
 	#start the process
 	$CMD
 	RETVAL=$?
-	[ $RETVAL = 0 ] && touch $LOCKFILE && success || failure
-	echo
+	[ $RETVAL = 0 ] && touch $LOCKFILE && echo "OK" || echo "ERROR"
 	if test -f $LOCKFILE ; then
 		# create the cron job to aggregate database data
 		crontab -l > /tmp/crontabo.txt
@@ -100,16 +102,17 @@ start() {
 
 # Restart the service
 stop() {
-	echo -n $"Stopping ServerUsage-Server: "
+	echo -n "Stopping ServerUsage-Server: "
 	# check if the process is running
-	if [ ! -z "`ps ax | grep -v grep | grep $PATH_TCPRECEIVER`" ]; then
+	if [ ! -z "$PID" ]; then
 		# kill the process
-		killproc $PATH_TCPRECEIVER
+		kill $PID
 		RETVAL=$?
+		echo "OK"
 	else
-		failure $"ServerUsage-Server stop"
+		RETVAL=3
+		echo "Service is not running."
 	fi
-	echo
 	rm -f $LOCKFILE
 	# remove the cron job
 	crontab -l > /tmp/crontabo.txt
@@ -129,8 +132,19 @@ case "$1" in
 		stop
 		;;
 	status)
-		status $CMD
-		RETVAL=$?
+		echo -n "ServerUsage-Server status: "
+		if [ ! -z "$PID" ]; then
+			RETVAL=0
+			echo "Service is running."
+		else
+			if test -f $LOCKFILE ; then
+				RETVAL=2
+				echo "Service is dead and $LOCKFILE lock file exist."
+			else
+				RETVAL=3
+				echo "Service is not running."
+			fi
+		fi
 		;;
 	restart|reload)
 		stop
@@ -143,7 +157,7 @@ case "$1" in
 		fi
 		;;
 	*)
-		echo $"Usage: $0 {start|stop|status|restart|reload|condrestart}"
+		echo "Usage: $0 {start|stop|status|restart|reload|condrestart}"
 		RETVAL=2
 		[ "$1" = 'usage' ] && RETVAL=0
 esac
